> [목차](index.md)
## 8. 예외처리
- [예외처리](#예외처리)
- [예외 처리하기 try_catch](#예외-처리하기-try_catch)
- [예외 발생시키기](#예외-발생시키기)
- [사용자 정의 예외만들기](#사용자-정의-예외만들기)
- [예외 되던지기 exception re_throwing](#예외-되던지기-exception-re_throwing)
- [연결된 예외](#연결된-예외)


<br><br>
<br><br>





# 예외처리
- 컴파일 에러(compile-time error) : 컴파일 할 때 발생하는 에러
- 런타임 에러(runtime error) : 프로그램의 실행도중에 발생하는 에러
  - 예외(execption) : 프로그램 코드에 의해서 수습될 수 있는 미약한 오류
  - 에러(error) : 프로그램 코드에 의해서 수습될 수 없는 심각한 오류
    - 메모리부족(OutOfMemory)
    - 스택오버플로우(StackOverflowError)
- 논리적 에러(logical error) : 의도한 것과 다르게 동작하는 것
    
<br>

## 예외 클래스의 계층구조
 - `Object` 클래스
  - `Throwable`
    - `Exception` : 사용자의 실수와 같은 외적인 요인에 의해 발생하는 예외
      - `RuntimeException` : 프로그래머의 실수로 발생하는 예외
        - `ArrayIndexOutOfNoundsException` : 배열의 범위를 벗어남
        - `ArithmeticException` : 정수를 0으로 나눔
        - `ClassCastException` : 클래스간의 형변환이 잘못됨
        - `NullPointerException` : null인 참조변수의 멤버를 호출시
      - `FileNotFoundException` : 파일의 이름이 존재하지 않음
      - `ClassNotFoundException` : 클래스이름을 잘못 적음
      - `DataFormatException` : 입력데이터 형식이 잘못됨
      - `IOException`...
    - `Error`
      - `OutOfMemoryError`...

<br><br>
<br><br>





# 예외 처리하기 try_catch
- 발생한 예외를 처리하지 못하면 프로그램은 비정상적으로 종료된다.
- try_catch문으로 예외처리를 하여 예외가 발생해도 비정상적으로 종료하지 않도록 한다.
- 처리되지 못한 예외(uncaght exception)는 JVM의 예외처리기(UncaughtExceptionHandler)가 받아서 예외의 원인을 화면에 출력한다.
```java
class Ex8_4 {
	public static void main(String args[]) {
		System.out.println(1);			
		System.out.println(2);
		try {
			System.out.println(3);
			System.out.println(0/0); // 에러 발생
			System.out.println(4); 	// 처리되지 않는다.
		} catch (ArithmeticException ae)	{ // 일치하는  
			if (ae instanceof ArithmeticException) 
				System.out.println("true");	
			  System.out.println("예외 메세지 : " + ae.getMessage());
			  System.out.println("ArithmeticException"); 
		} catch (Exception e){
			System.out.println("Exception");
		}	
		System.out.println(6);
}
```  
- try블럭 내에서 예외가 발생한 경우
  1. 발생한 예외에 해당하는 클래스의 인스턴스`ArithmeticException`가 만들어 진다.
  2. catch블럭 내 참조변수의 종류와 `instanceof`연산자를 이용해서 true가 나올때까지 검사하고 일치하면 수행하고 빠져나온다.
    - ( 첫 번째 검사에서 일치하는 catch블럭을 찾으면 다음번째 catch블럭은 검사하지 않는다. )
  3. 모든 예외 클래스는 `Exception`의 자손이므로 어떤 종류의 예외가 발생하더라도 처리한다.
- `printStackTrace() : 예외발생 당시의 호출스택(Call Stack)에 있었던 메서드의 정보와 예외 메세지를 출력
- `getMessage()` : 발생한 예외클래스의 인스턴스에 저장된 메시지를 얻을 수 있다.

<br>

## 멀티 catch블럭
- 멀티 catch블럭 내에서는 실제로 어떤 예외가 발생한 것인지 알 수 없다.
- 멀티로 연결된 예외 클래스들은 공통분모인 조상 예외 클래스에 선언된 멤버만 사용할 수 있다.
```java
try{
  ... 
} catch(ExecptionA | ExceptionB e){
    //e.methodA(); // ExceptionA에 선언된 methodA()는 호출불가
    if(e instaceof Execption){
      ExceptionA e1 = (ExceptionA)e;
      e1.methodA(); // ExceptionA에 선언된 메서드 호출가능
    }
    e.printStackTrace();
}
```

<br><br>
<br><br>






# 예외 발생시키기
```java
class Ex8_6 {
	public static void main(String args[]) {
		try {
			Exception e = new Exception("고의적 발생");
			throw e;	 // 고의적 예외 발생
		//  throw new Exception("고의적 발생"); // 줄여서

		} catch (Exception e)	{
			System.out.println("에러 메세지 : " + e.getMessage());
			e.printStackTrace();
		} finally {
      // 예외의 발생여부에 상관없이 수행됨
    }
		System.out.println("프로그램이 정상 종료되었음.");
	}
}
```
> :grey_question: `RuntimeException`클래스와 그 자손(unchecked예외)에 해당하는 예외는 프로그래머가 실수로 발생하는 것들이기 때문에
예외처리를 강제하지 않는 것이다. 만일 `RuntimeException`클래스들에 속하는 예외가 발생할 가능성이 있는 코드에도 예외처리를 해야 한다면,
아래와 같이 참조 변수와 배열이 사용되는 모든 곳에 예외처리를 해주어야 할 것이다.

```java
try {
  int[] arr = new int[10];
  System.out.println(arr[0]);
} catch (IndexOutOfBoundException e) { ~ }
} catch (IndexOutOfBoundException e) { ~ }
```

<br><br>
<br><br>







# 사용자 정의 예외만들기
> :bulb: `Exception`을 상속받는 checked예외처리는 반드시 예외처리(try_catch)를 해줘야만 하지만 `RuntimeException`은 선택적으로 할 수 있다.
```java
class Ex8_11 {
	public static void main(String args[]) {
		try {
			startInstall();	
			copyFiles();	
		} catch (SpaceException e)	{
			System.out.println("에러메세지 : " + e.getMessage());
			e.printStackTrace();
			System.out.println("공간을 확보한 후에 다시 설치하시기 바랍니다.");
		} catch (MemoryException me)	{
			System.out.println("에러 메세지: " + me.getMessage());
			me.printStackTrace();
			System.gc();         // Garbage Collection
			System.out.println("다시 설치를 시도하세요.");
		} finally {
			deleteTempFiles();
		} 
	}

   static void startInstall() throws SpaceException, MemoryException { 
		if(!enoughSpace()) 		
			throw new SpaceException("설치할 공간이 부족합니다."); // 에러 발생
		if (!enoughMemory())		
			throw new MemoryException("메모리가 부족합니다."); // 에러 발생
   } 

   static void copyFiles() { ~ }
   static void deleteTempFiles() { ~ }
   
   static boolean enoughSpace()   
		return false;
   }
	static boolean enoughMemory() {
		return true;
   }
}

class SpaceException extends Exception {
	SpaceException(String msg) { // 메세지를 저장하기 위해 String 매개변수를 추가
	   super(msg);	// 조상인 Exception클래스의 생성자를 호출한다.
   }
}

class MemoryException extends Exception {
	MemoryException(String msg) {
	   super(msg);	
   }
}
```

<br><br>
<br><br>







# 예외 되던지기 exception re_throwing
```java
class Ex8_12 {
	public static void main(String[] args) {
		try  {
			int v = method1(); // 되받기
		} catch (Exception e)	{
			System.out.println("main메서드에서 예외가 처리되었습니다."); // 순서 2
		}
	}	

	static int method1() throws Exception {
		try {
			throw new Exception();
			return 0;
		} catch (Exception e) {
			System.out.println("method1메서드에서 예외가 처리되엇습니다.."); // 순서 1
			throw e; // 되던지기
			return 1; // catch블럭 내에도 return문이 필요하다.
		}
	}
}
```

<br><br>
<br><br>







# 연결된 예외
- 한 예외가 다른 예외를 발생시킬 수 있다.
- `예외A`가 `예외B`를 발생시켰다면, A를 B의 원인예외(cause Exception)이라고 한다.
- 여러가지 예외를 하나의 큰 분류의 예외로 묶어서 다루기 위함이다.
```java
try{
	startInstall();
	copyFiles();
}catch(SpaceException){ // 예외 발생
	InstallException ie = new InstallException("설치중 예외발생"); // 예외 생성
	ie.initCause(e); // InstallException의 원인 예외를 SpaceException로 지정
	throw ie; // InstallException을 발생시킨다. (상속관계)
}catch(MemoryException){ }
```
```java
// 예외가 원인 예외를 포함하는 방법, 상속관계가 아니어도 상관없다.
public class Throwable implements Serializable{
	private Thorwable cause = this; // 객체 자신(this)를 원인 예외로 등록
}
```
- checked예외를 uncheked예외로 바꾸기 위함이다. (예외처리는 선택적이게 된다.)
```java
static void startInstall() throws SpaceException, MemoryException{
	if(!enoughSpace())
		throw new SpaceException("설치할 공간이 부족합니다.");
	if(!enoughMemory())
		throw new MemoryException("메모리가 부족합니다."); // Exception의 자손이므로 반드시 예외처리를 해야함
}
```
```java
static void startInstall() throws SpaceException{
	if(!enoughSpace())
		throw new SpaceException("설치할 공간이 부족합니다.");
	if(!enoughMemory())
		throw new RuntimeException(new MemoryException("메모리가 부족합니다.")); //unchecked예외가 됨
}
```